import { Providers } from "@/components/Provider";
import "./globals.css";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import Navbar from "@/components/Navbar";

const ubuntu = Ubuntu({
  weight: ["400"],
  display: "auto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Gateverse - Learn and try</title>
        <meta name="description" content="Blog related to gate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={ubuntu.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
